version: "3"

services:
  ci-server:
    build: ./ci-server
    image: ci-server
    ports:
      - "8085:8085"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ci-server/test:/ci-server/test

  committer-report:
    build: ./monitoring/committer_report
    image: monitoring/committer_report
    ports:
      - "8084:8084"

  monitor:
    build: ./monitoring
    image: monitoring
    ports:
      - "8083:8083"

