version: "3.3"

services:
  flask-server:
    build: ./weight/
    container_name: flask-server
    ports:
      - "5000:5000"
    volumes:
      - data:/data
    depends_on:
      - db
    expose:
      - "5000"
    environment:
      - "FLASK_APP=app.py"
  
  db:
    image: mysql:8.0
    container_name: DB
    ports:
      - "3306:3306"
    volumes:
      - data:/data
      - ./db.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - "MYSQL_DATABASE=weightDB"
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=alpine"
    expose:
      - "3306"

volumes:
  data:
    


