version: "3.3"

services:
  app:
    build: ./weight/
    container_name: app
    ports:
      - "8080:5000"
    volumes:
      - data:/data
    depends_on:
      - db
    expose:
      - "5000"
    environment:
      - "FLASK_APP =app.py"
  
  db:
    image: mysql:8.0
    container_name: DB
    ports:
      - "8081:3306"
    volumes:
      - data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - "MYSQL_DATABASE=weightDB"
      - "MYSQL_USER=user"
      - "MYSQL_ROOT_PASSWORD=alpine"
    expose:
      - "3306"

volumes:
  data:
    


